name: Deploy Image to ECR 

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: "if no confirmation, exit"
      run: |
        if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
          echo "Exiting without deployment"
          exit 1
        fi
      shell: bash

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Retrieve VITE_RAPID_API_KEY from Secrets Manager
      run: |
        API_KEY=$(aws secretsmanager get-secret-value \
          --secret-id delta-api-key \
          --query 'SecretString' \
          --output text | grep -oP '"VITE_RAPID_API_KEY"\s*:\s*"\K[^"]+')
    
        echo "VITE_RAPID_API_KEY=$VITE_RAPID_API_KEY" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Image
      run: |
        docker build -t "${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }}" --build-arg VITE_RAPID_API_KEY="${{ env.VITE_RAPID_API_KEY }}" .    
      
    - name: Push Image to Amazon ECR
      run: |
        docker push "${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }}"
